CREATE TABLE IF NOT EXISTS id_generated_entities (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	str VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	username VARCHAR(64) PRIMARY KEY,
	password VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS chunk_entities (
	id VARCHAR(64) PRIMARY KEY,
	num BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS preprocess_entities (
	id VARCHAR(64) PRIMARY KEY,
	str VARCHAR(64) NOT NULL,
	last_updated BIGINT NOT NULL
);
